version: "3.1"

services:
  catalog-server-1:
    build:
      context: ./catalog_server
      dockerfile: Dockerfile
    image: catalog-server-image:1.0
    ports:
      - "3001:3000"
    networks:
      bazar-network:
        aliases:
          - catalog-server-1

  catalog-server-2:
    build:
      context: ./catalog_server
      dockerfile: Dockerfile
    image: catalog-server-image:1.0
    ports:
      - "3002:3000"
    networks:
      bazar-network:
        aliases:
          - catalog-server-2

  order-server-1:
    build:
      context: ./order_server
      dockerfile: Dockerfile
    image: order-server-image:1.0
    ports:
      - "8081:8081"
    networks:
      bazar-network:
        aliases:
          - order-server-1

  order-server-2:
    build:
      context: ./order_server
      dockerfile: Dockerfile
    image: order-server-image:1.0
    ports:
      - "8082:8081"
    networks:
      bazar-network:
        aliases:
          - order-server-2

  frontend-server:
    build:
      context: ./frontend_server
      dockerfile: Dockerfile
    image: frontend-server-image:1.0
    ports:
      - "8082:8082"
    networks:
      bazar-network:
        aliases:
          - frontend-server

networks:
  bazar-network:
    external: false
