version: "3.1"

services:
  catalog-server:
    build:
      context: ./catalog_server
      dockerfile: Dockerfile
    image: catalog-server-image:1.0
    ports:
      - "3000:3000"
    networks:
      - bazar-network
    # Uncomment to persist data if needed
    # volumes:
    #   - ./catalog_server:/catalog_server:ro
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/bazar"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3

  order-server:
    build:
      context: ./order_server
      dockerfile: Dockerfile
    image: order-server-image:1.0
    ports:
      - "8081:8081"
    networks:
      - bazar-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/bazar"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3

  frontend-server:
    build:
      context: ./frontend_server
      dockerfile: Dockerfile
    image: frontend-server-image:1.0
    ports:
      - "8082:8082"
    networks:
      - bazar-network
    # Uncomment to persist data if needed
    # volumes:
    #   - ./frontend_server:/frontend_server:ro
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8082/api/v1/bazar"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3

networks:
  bazar-network:
    external: false
