version: "3.1"

services:
  catalog-server:
    build:
      context: ./catalog_server
      dockerfile: Dockerfile
    image: catalog-server-image:1.0
    ports:
      - "3000:3000" # First replica
      - "3001:3000" # Second replica
    networks:
      - bazar-network
    deploy:
      replicas: 2

  order-server:
    build:
      context: ./order_server
      dockerfile: Dockerfile
    image: order-server-image:1.0
    ports:
      - "8081:8081" # First replica
      - "8082:8081" # Second replica
    networks:
      - bazar-network
    deploy:
      replicas: 2

  frontend-server:
    build:
      context: ./frontend_server
      dockerfile: Dockerfile
    image: frontend-server-image:1.0
    ports:
      - "8082:8082"
    networks:
      - bazar-network
    depends_on:
      - catalog-server
      - order-server

networks:
  bazar-network:
    driver: bridge
