version: "3.1"

services:
  catalog-server-1:
    build:
      context: ./catalog_server
    image: catalog-server-image:1.0
    ports:
      - "3001:3000"
    volumes:
      - ./catalog_server:/app
    networks:
      - bazar-network

  catalog-server-2:
    build:
      context: ./catalog_server
    image: catalog-server-image:1.0
    ports:
      - "3002:3000"
    volumes:
      - ./catalog_server:/app
    networks:
      - bazar-network

  order-server-1:
    build:
      context: ./order_server
    image: order-server-image:1.0
    ports:
      - "8081:8081"
    volumes:
      - ./order_server:/app
    networks:
      - bazar-network

  order-server-2:
    build:
      context: ./order_server
    image: order-server-image:1.0
    ports:
      - "8082:8081"
    volumes:
      - ./order_server:/app
    networks:
      - bazar-network

  frontend-server:
    build:
      context: ./frontend_server
    image: frontend-server-image:1.0
    ports:
      - "8083:8082"
    volumes:
      - ./frontend_server:/app
    networks:
      - bazar-network

networks:
  bazar-network:
    external: false
